version: "3.9"

services:
  db:
    container_name: mongo_flask_ollivanders
    image: mongo
    volumes:
      - mongo_ollivanders:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      
    ports:
      - "27017:27017"
    networks:
      - docker_ollivanders_flask

  api:
    container_name: ollivanders-flask
    image: ollivanders-flask
    environment:
      URI: ${URI}
    ports:
      - "5000:5000"
    networks:
      - docker_ollivanders_flask

networks:
  docker_ollivanders_flask:

volumes:
  mongo_ollivanders: